services:
  - type: web
    name: stock-market-intelligence-2
    env: python
    pythonVersion: "3.10"
    buildCommand: pip install -r requirements.txt && python data/fetch_data.py && python notebooks/04_portfolio_risk.py
    startCommand: python dashboard/app.py
    plan: free
